branch-defaults:
  default:
    environment: image-filter-starter-code1-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image-filter-starter-code1
  branch: null
  default_ec2_keyname: AWS_EC2_Demo
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
